# Deploy the opinionated coder website to AWS s3 bucket 
# The workflow Creates static website using aws s3
name: AWS example workflow
on:
  push
env:
  BUCKET_NAME : "arn:aws:s3:eu-west-1:777920111935:accesspoint/github"
  AWS_REGION : "eu-west-1"

# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          ache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::777920111935:role/OpinionatedCoderS3FullAccess
          role-session-name: deploytos3
          aws-region: ${{ env.AWS_REGION }}
      # Upload a file to AWS s3
      - name:  Copy index.html to s3
        run: |
          aws s3 sync ./dist s3://${{ env.BUCKET_NAME }}/